/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as AuthedGuildsGuildIdRouteRouteImport } from './routes/_authed/guilds/$guildId/route'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthedGuildsGuildIdSettingsIndexRouteImport } from './routes/_authed/guilds/$guildId/settings/index'

const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedGuildsGuildIdRouteRoute =
  AuthedGuildsGuildIdRouteRouteImport.update({
    id: '/guilds/$guildId',
    path: '/guilds/$guildId',
    getParentRoute: () => AuthedRoute,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedGuildsGuildIdSettingsIndexRoute =
  AuthedGuildsGuildIdSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthedGuildsGuildIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/login': typeof LoginRoute
  '/guilds/$guildId': typeof AuthedGuildsGuildIdRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/guilds/$guildId/settings/': typeof AuthedGuildsGuildIdSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/': typeof AuthedIndexRoute
  '/guilds/$guildId': typeof AuthedGuildsGuildIdRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/guilds/$guildId/settings': typeof AuthedGuildsGuildIdSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/guilds/$guildId': typeof AuthedGuildsGuildIdRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_authed/guilds/$guildId/settings/': typeof AuthedGuildsGuildIdSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/guilds/$guildId'
    | '/api/auth/$'
    | '/guilds/$guildId/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/'
    | '/guilds/$guildId'
    | '/api/auth/$'
    | '/guilds/$guildId/settings'
  id:
    | '__root__'
    | '/_authed'
    | '/login'
    | '/_authed/'
    | '/_authed/guilds/$guildId'
    | '/api/auth/$'
    | '/_authed/guilds/$guildId/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/guilds/$guildId': {
      id: '/_authed/guilds/$guildId'
      path: '/guilds/$guildId'
      fullPath: '/guilds/$guildId'
      preLoaderRoute: typeof AuthedGuildsGuildIdRouteRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/guilds/$guildId/settings/': {
      id: '/_authed/guilds/$guildId/settings/'
      path: '/settings'
      fullPath: '/guilds/$guildId/settings/'
      preLoaderRoute: typeof AuthedGuildsGuildIdSettingsIndexRouteImport
      parentRoute: typeof AuthedGuildsGuildIdRouteRoute
    }
  }
}

interface AuthedGuildsGuildIdRouteRouteChildren {
  AuthedGuildsGuildIdSettingsIndexRoute: typeof AuthedGuildsGuildIdSettingsIndexRoute
}

const AuthedGuildsGuildIdRouteRouteChildren: AuthedGuildsGuildIdRouteRouteChildren =
  {
    AuthedGuildsGuildIdSettingsIndexRoute:
      AuthedGuildsGuildIdSettingsIndexRoute,
  }

const AuthedGuildsGuildIdRouteRouteWithChildren =
  AuthedGuildsGuildIdRouteRoute._addFileChildren(
    AuthedGuildsGuildIdRouteRouteChildren,
  )

interface AuthedRouteChildren {
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedGuildsGuildIdRouteRoute: typeof AuthedGuildsGuildIdRouteRouteWithChildren
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedGuildsGuildIdRouteRoute: AuthedGuildsGuildIdRouteRouteWithChildren,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
